# Generated by Django 4.0.8 on 2024-02-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='shop/', verbose_name='Картинка'),
        ),
    ]
