# Generated by Django 4.0.8 on 2024-03-01 07:42

import django.core.validators
from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_slug_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-is_available', '-time_create'), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='shop/default.jpg', upload_to=shop.models.Product.get_file_path, validators=[shop.models.Product.validate_image, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg'], message='Данный формат файла не поддерживается')], verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Используйте буквы только латинского и русского алфавита', regex='[^a-zA-ZА-Яа-яЁё0-9 ]')], verbose_name='Название'),
        ),
    ]
